WITH RECURSIVE Generation AS (
  SELECT ID, PARENT_ID, 1 AS GEN
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL
  UNION ALL
  SELECT e.ID, e.PARENT_ID, g.GEN + 1
  FROM ECOLI_DATA e
  JOIN Generation g ON e.PARENT_ID = g.ID
)
SELECT ID
FROM Generation
WHERE GEN = 3
ORDER BY ID;
