SELECT USER_ID, PRODUCT_ID
FROM (
  SELECT USER_ID, PRODUCT_ID, COUNT(*) AS PURCHASE_COUNT
  FROM ONLINE_SALE
  GROUP BY USER_ID, PRODUCT_ID
) AS PURCHASES
WHERE PURCHASE_COUNT > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;