SELECT CASE WHEN f < 1 THEN '0'
            WHEN f >= 1 THEN f * 10000
            ELSE NULL END PRICE_GROUP,
            COUNT(*) PRODUCTS
FROM ( SELECT FLOOR(PRICE / 10000) f
       FROM PRODUCT) a
GROUP BY 1
ORDER BY 1;